function fo = FO(t,in2,in3,in4,in5,in6,in7)
%FO
%    FO = FO(T,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Apr-2024 16:39:41

GHhx = in4(:,3);
GHhy = in4(:,4);
GHsx = in4(:,1);
GHsy = in4(:,2);
c = in3(:,6);
g = in3(:,5);
mh = in3(:,2);
qq1 = in2(1,:);
qq2 = in2(2,:);
uu1 = in2(3,:);
uu2 = in2(4,:);
t2 = cos(qq1);
t3 = cos(qq2);
t4 = sin(qq1);
t5 = sin(qq2);
t6 = uu1+uu2;
t7 = uu1.^2;
t8 = GHhx.*t3;
t9 = GHhy.*t3;
t10 = GHhx.*t5;
t11 = GHhy.*t5;
t12 = t2.*t3;
t13 = t2.*t5;
t14 = t3.*t4;
t15 = t4.*t5;
t16 = t6.^2;
t17 = -t11;
t18 = -t15;
t19 = t9+t10;
t21 = t13+t14;
t20 = t8+t17;
t22 = t12+t18;
t23 = GHhy.*g.*mh.*t21;
t24 = GHsx.*mh.*t7.*t19;
t25 = GHhx.*g.*mh.*t22;
t26 = -t23;
t27 = GHsy.*mh.*t7.*t20;
t28 = -t27;
fo = [uu1;uu2;t24+t25+t26+t28-c.*uu1+GHhx.*mh.*t16.*(GHsy.*t3-GHsx.*t5)-GHhy.*mh.*t16.*(GHsx.*t3+GHsy.*t5)-GHsx.*g.*mh.*t2+GHsy.*g.*mh.*t4;t24+t25+t26+t28-c.*uu2];
end
