function torque = Inverse_dyn(t,in2,in3,in4)
%Inverse_dyn
%    TORQUE = Inverse_dyn(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    21-Mar-2024 15:58:10

GHhx = in4(:,3);
GHhy = in4(:,4);
GHsx = in4(:,1);
GHsy = in4(:,2);
Ih = in3(:,4);
Is = in3(:,3);
c = in3(:,6);
ddq1 = in2(5,:);
ddq2 = in2(6,:);
g = in3(:,5);
mh = in3(:,2);
qq1 = in2(1,:);
qq2 = in2(2,:);
uu1 = in2(3,:);
uu2 = in2(4,:);
t2 = cos(qq1);
t3 = cos(qq2);
t4 = sin(qq1);
t5 = sin(qq2);
t6 = uu1+uu2;
t7 = GHhx.^2;
t8 = GHhy.^2;
t9 = uu1.^2;
t10 = GHhx.*t3;
t11 = GHhy.*t3;
t12 = GHsx.*t3;
t13 = GHsy.*t3;
t14 = GHhx.*t5;
t15 = GHhy.*t5;
t16 = GHsx.*t5;
t17 = GHsy.*t5;
t18 = t2.*t3;
t19 = t2.*t5;
t20 = t3.*t4;
t21 = t4.*t5;
t22 = t6.^2;
t25 = -t15;
t26 = -t16;
t27 = -t21;
t28 = t11+t14;
t29 = t12+t17;
t34 = t19+t20;
t30 = GHsy.*t28;
t31 = GHhx.*t29;
t32 = t10+t25;
t33 = t13+t26;
t37 = t18+t27;
t38 = GHhy.*g.*mh.*t34;
t39 = GHsx.*mh.*t9.*t28;
t35 = GHsx.*t32;
t36 = GHhy.*t33;
t40 = GHhx.*g.*mh.*t37;
t41 = -t39;
t42 = GHsy.*mh.*t9.*t32;
t43 = -t40;
torque = [t38+t41+t42+t43+ddq2.*(Ih+mh.*(t7+t8-t30-t35))+c.*uu1+ddq1.*(Ih+Is+mh.*(t7+t8-t30-t31-t35-t36+GHsx.^2+GHsy.^2))+GHsx.*g.*mh.*t2-GHsy.*g.*mh.*t4+GHhy.*mh.*t22.*t29-GHhx.*mh.*t22.*t33;t38+t41+t42+t43+ddq1.*(Ih+mh.*(t7+t8-t31-t36))+c.*uu2+ddq2.*(Ih+mh.*(t7+t8))];
end
