function torque = Inverse_dyn(t,in2,in3,in4)
%Inverse_dyn
%    TORQUE = Inverse_dyn(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Mar-2024 14:19:14

F1 = in3(:,1);
F2 = in3(:,2);
c1 = in4(:,4);
c2 = in4(:,5);
ddq1 = in2(5,:);
ddq2 = in2(6,:);
g = in4(:,3);
k1 = in4(:,6);
k2 = in4(:,7);
l = in4(:,1);
m = in4(:,2);
qq1 = in2(1,:);
qq2 = in2(2,:);
uu1 = in2(3,:);
uu2 = in2(4,:);
t2 = cos(qq1);
t3 = cos(qq2);
t4 = sin(qq1);
t5 = sin(qq2);
t6 = l.^2;
t7 = uu1.^2;
t8 = t2.*t3;
t9 = t4.*t5;
t11 = t6./4.0;
t12 = (t3.*t6)./2.0;
t13 = (m.*t5.*t6.*t7)./2.0;
t10 = -t9;
t15 = t11+t12;
t14 = t8+t10;
t16 = (g.*l.*m.*t14)./2.0;
torque = [-F1+t13+t16+c1.*uu1+k1.*qq1+ddq1.*(m.*t11+m.*(t6.*(5.0./4.0)+t3.*t6))+ddq2.*m.*t15+g.*l.*m.*t2.*(3.0./2.0)-(m.*t5.*t6.*(uu1+uu2).^2)./2.0;-F2+t13+t16+c2.*uu2+k2.*qq2+ddq2.*m.*t11+ddq1.*m.*t15];
end
