function mm = MM(t,in2,in3,in4,in5,in6,in7)
%MM
%    MM = MM(T,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Apr-2024 17:56:00

GHhx = in4(:,3);
GHhy = in4(:,4);
GHsx = in4(:,1);
GHsy = in4(:,2);
Ih = in3(:,4);
Is = in3(:,3);
mh = in3(:,2);
qq2 = in2(2,:);
t2 = cos(qq2);
t3 = sin(qq2);
t4 = GHhx.^2;
t5 = GHhy.^2;
t6 = GHhx.*t2;
t7 = GHhy.*t2;
t8 = GHsx.*t2;
t9 = GHsy.*t2;
t10 = GHhx.*t3;
t11 = GHhy.*t3;
t12 = GHsx.*t3;
t13 = GHsy.*t3;
t16 = -t11;
t17 = -t12;
t18 = t7+t10;
t19 = t8+t13;
t20 = GHsy.*t18;
t21 = GHhx.*t19;
t22 = t6+t16;
t23 = t9+t17;
t24 = GHsx.*t22;
t25 = GHhy.*t23;
mm = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Ih+Is+mh.*(t4+t5-t20-t21-t24-t25+GHsx.^2+GHsy.^2),Ih+mh.*(t4+t5-t21-t25),0.0,0.0,Ih+mh.*(t4+t5-t20-t24),Ih+mh.*(t4+t5)],[4,4]);
end
