function dq = ODE_sim(t,in2,in3,in4)
%ODE_sim
%    DQ = ODE_sim(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Mar-2024 14:19:14

F1 = in3(1,:);
F2 = in3(2,:);
c1 = in4(:,4);
c2 = in4(:,5);
g = in4(:,3);
k1 = in4(:,6);
k2 = in4(:,7);
l = in4(:,1);
m = in4(:,2);
qq1 = in2(1,:);
qq2 = in2(2,:);
uu1 = in2(3,:);
uu2 = in2(4,:);
t2 = cos(qq1);
t3 = cos(qq2);
t4 = sin(qq1);
t5 = sin(qq2);
t6 = F1.*2.0;
t7 = l.^2;
t8 = uu1.^2;
t9 = uu2.^2;
t11 = c1.*uu1.*2.0;
t12 = k1.*qq1.*2.0;
t13 = 1.0./m;
t10 = t3.^2;
t14 = -t11;
t15 = -t12;
t16 = g.*l.*m.*t2.*3.0;
t18 = m.*t5.*t7.*t9;
t19 = m.*t5.*t7.*uu1.*uu2.*2.0;
t20 = g.*l.*m.*t3.*t4.*t5.*2.0;
t17 = -t16;
t21 = g.*l.*m.*t2.*t10.*2.0;
t22 = -t20;
dq = [uu1;uu2;(t13.*(F2.*-2.0+t6+t14+t15+t17+t18+t19+t21+t22-F2.*t3.*4.0+c2.*uu2.*2.0+k2.*qq2.*2.0+c2.*t3.*uu2.*4.0+k2.*qq2.*t3.*4.0+m.*t5.*t7.*t8+m.*t3.*t5.*t7.*t8.*2.0).*-2.0)./(t7.*(t10.*4.0-5.0));(t13.*(F2.*-1.2e+1+t6+t14+t15+t17+t18+t19+t21+t22+F1.*t3.*4.0-F2.*t3.*8.0+c2.*uu2.*1.2e+1+k2.*qq2.*1.2e+1+t3.*t18.*2.0-c1.*t3.*uu1.*4.0+c2.*t3.*uu2.*8.0-k1.*qq1.*t3.*4.0+k2.*qq2.*t3.*8.0+m.*t5.*t7.*t8.*6.0-g.*l.*m.*t2.*t3-g.*l.*m.*t4.*t5.*5.0+m.*t3.*t5.*t7.*t8.*4.0+m.*t3.*t5.*t7.*uu1.*uu2.*4.0).*-2.0)./(t7.*5.0-t7.*t10.*4.0)];
end
