function react_angle = phi_react(in1,in2,data_sym)
%PHI_REACT
%    REACT_ANGLE = PHI_REACT(IN1,IN2,DATA_SYM)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2024 16:24:07

qq1 = in1(:,1);
qq2 = in1(:,2);
uu1 = in1(:,3);
uu2 = in1(:,4);
t2 = cos(qq1);
t3 = cos(qq2);
t4 = sin(qq1);
t5 = sin(qq2);
t6 = uu1.^2;
t7 = uu2.^2;
t8 = t3./5.0e+1;
t9 = t5./5.0e+1;
t11 = t2.*t5.*uu1.*uu2.*(2.0./5.0);
t12 = t3.*t4.*uu1.*uu2.*(2.0./5.0);
t13 = t2.*t6.*(3.0./2.0e+1);
t14 = t4.*t5.*uu1.*uu2.*(2.0./5.0);
t15 = t4.*t6.*(3.0./2.0e+1);
t16 = t2.*t3.*uu1.*uu2.*(2.0./5.0);
t17 = (t2.*t3.*t6)./5.0;
t18 = (t2.*t3.*t7)./5.0;
t19 = (t2.*t5.*t6)./5.0;
t20 = (t3.*t4.*t6)./5.0;
t21 = (t2.*t5.*t7)./5.0;
t22 = (t3.*t4.*t7)./5.0;
t24 = (t4.*t5.*t6)./5.0;
t25 = (t4.*t5.*t7)./5.0;
t26 = t2.*t6.*5.6e-3;
t27 = t4.*t6.*5.6e-3;
t10 = -t9;
t23 = -t16;
t28 = -t17;
t29 = -t18;
t30 = -t27;
t32 = t8+t9-1.72e-2;
t31 = t8+t10+1.7e+1./2.0e+2;
t34 = t32.^2;
t40 = t11+t12+t13+t19+t20+t21+t22+t30;
t41 = t14+t15+t23+t24+t25+t26+t28+t29;
t33 = t31.^2;
t35 = t33+t34;
t36 = sqrt(t35);
t37 = t36.*7.619047619047619e+1;
t38 = t37-1.29e+2./1.0e+1;
t39 = exp(t38);
react_angle = (atan((t2.*1.96133e+1-t2.*t41+t4.*t40+t32.*t35.*t39.*6.046863189720333e+5)./(t4.*1.96133e+1-t2.*t40-t4.*t41+t31.*t35.*t39.*6.046863189720333e+5)).*1.8e+2)./pi;
end
